-- =============================================================================
-- print_orders — one row per "ship me a printed copy" request.
-- =============================================================================
-- Created by the Stripe webhook when checkout.session.completed includes
-- `print` in the chosen outputs. The webhook also writes the Lulu xPress
-- print-job id once we've POSTed to Lulu. Downstream Lulu status webhooks
-- (Phase 4d-followup or Phase 5) update `status` + `tracking_url`.
-- =============================================================================

create table if not exists public.print_orders (
  id uuid primary key default gen_random_uuid(),
  zine_id uuid not null references public.zines(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  /* Stripe checkout that paid for the order. Useful when reconciling
     payments to fulfillment. Nullable for orders made under an annual
     subscription where each issue isn't a separate Checkout Session. */
  stripe_session_id text,
  /* The Lulu print-job id we get back from POST /print-jobs/. Nullable
     until the webhook successfully submits the order. */
  lulu_print_job_id text unique,
  /* Shipping address Stripe collected at checkout, stored as JSONB so we
     can keep the full shape Stripe returns without forcing a tabular
     layout. */
  shipping_address jsonb,
  /* Pipeline status — narrower than Lulu's lifecycle, just enough for the
     UI to show progress. */
  status text not null default 'pending'
    check (status in (
      'pending',        -- row created, not yet submitted to Lulu
      'rendering',      -- PDF being generated by our renderer
      'uploading',      -- PDF being uploaded to Storage
      'submitted',      -- POST /print-jobs/ returned 201
      'in_production',  -- Lulu confirmed accepted
      'shipped',        -- tracking_url present
      'delivered',
      'failed'
    )),
  status_detail text,           -- last error message or note for human review
  tracking_url text,            -- Lulu carrier tracking URL once shipped
  cover_pdf_url text,           -- signed URL we gave Lulu (may expire)
  cover_pdf_md5 text,           -- md5 of the rendered PDF, required by Lulu
  pod_package_id text,          -- which Lulu product (e.g. magazine saddle stitch)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.print_orders is
  'Tracks the lifecycle of a printed-copy request from Stripe payment through Lulu xPress fulfillment.';

create index if not exists print_orders_zine_id_idx on public.print_orders(zine_id);
create index if not exists print_orders_user_id_idx on public.print_orders(user_id);
create index if not exists print_orders_status_idx on public.print_orders(status);

create trigger print_orders_set_updated_at
  before update on public.print_orders
  for each row execute function public.set_updated_at();

-- RLS — owner read-only. The webhook + Lulu updaters use the service
-- role so they bypass these policies.
alter table public.print_orders enable row level security;

create policy "print_orders: owner can select"
  on public.print_orders for select
  using (user_id = (select auth.uid()));

-- =============================================================================
-- Storage bucket for the rendered PDF artifacts.
-- =============================================================================
-- We upload each generated PDF here, then hand Lulu a signed URL. The
-- bucket is private — Lulu fetches the PDF via a time-bounded signed
-- URL we mint at submission time.
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('zine-pdfs', 'zine-pdfs', false)
on conflict (id) do nothing;

-- No RLS policies on the bucket — only the service role writes/reads
-- (via the admin client + signed URLs). Public access is gated by the
-- signed URL itself.
